import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
  await page.getByText('Notes').click();
  await page.locator('dc-combobox').filter({ hasText: 'FilterView all notesView my' }).getByLabel('expand').click();
  await page.getByText('View my notes').click();
  await page.locator('dc-combobox').filter({ hasText: 'FilterView all notesView my' }).getByLabel('expand').click();
  await page.getByText('View deleted notes').click();
  await page.getByText('Tasks').click();
  await page.getByRole('textbox', { name: 'Queues:' }).click();
  await page.getByText('View All Queues').click();
  await page.locator('#dc-sect5').getByRole('textbox', { name: 'Due:' }).click();
  await page.locator('#cb_4_options').getByText('View All Tasks').click();
  await page.locator('#action_19').getByRole('link', { name: 'More Options' }).click();
  await page.locator('dc-combobox').filter({ hasText: 'Category:(Select)' }).getByLabel('expand').click();
  await page.getByText('General').click();
  await page.locator('dc-combobox').filter({ hasText: 'State:' }).getByLabel('expand').click();
  await page.getByText('All', { exact: true }).click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('link', { name: 'My Tasks' }).click();
  await page.getByRole('link', { name: 'My Agenda' }).click();
  await page.getByText('21/03 Friday').click();
  await page.getByText('23/03 Sunday').click();
  await page.getByText('6/04 Sunday').click();
  await page.getByText('19/04 Saturday').click();
  await page.getByRole('link', { name: 'Task Management' }).click();
  await page.locator('#dc-sect13').getByRole('button', { name: 'expand' }).click();
  await page.getByRole('row', { name: 'Selected  Internal Users' }).getByLabel('Selected').check();
  await page.locator('#dc-sect13').getByRole('button', { name: 'expand' }).click();
  await page.getByText('Search', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Match Value' }).click();
  await page.getByRole('textbox', { name: 'Match Value' }).fill('D');
  await page.getByText('Def').click();
  await page.getByRole('row', { name: ' MI000072 DR abc def' }).locator('dc-drop-button').getByRole('button').click();
  await page.getByText('View Policy', { exact: true }).click();
  await page.goto('http://localhost/Policy/error');
  await page.getByText('Search').click();
  await page.getByRole('link', { name: 'Basic Search' }).click();
  await page.getByRole('link', { name: 'Advanced Search' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByText('Insured name').click();
  await page.locator('dc-combobox').filter({ hasText: 'OperationContainsIsIs notEnds' }).getByLabel('expand').click();
  await page.getByText('Contains').click();
  await page.getByRole('textbox', { name: 'Value' }).click();
  await page.getByRole('textbox', { name: 'Value' }).fill('Dr');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'Basic Search' }).click();
  await page.getByRole('textbox', { name: 'Match Value' }).click();
  await page.getByRole('textbox', { name: 'Match Value' }).fill('Dr');
  await page.getByText('Dr').click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('row', { name: ' MI000072 DR abc def' }).locator('dc-drop-button').getByRole('button').click();
  await page.getByText('View Policy Details').click();
  await page.goto('http://localhost/Policy/error');
  await page.getByRole('link', { name: 'Home' }).click();
  await page.locator('dc-hypergrid-row:nth-child(5) > .table-row > dc-hypergrid-cell:nth-child(2) > .field-container > .field > .control-container > .control').click();
  await page.getByRole('link', { name: 'MI993Q2025' }).click();
  await page.locator('iframe[name="classicFrame"]').contentFrame().locator('#errorDetailsSection_toggleHeader').click();
  await page.locator('iframe[name="classicFrame"]').contentFrame().getByRole('button', { name: 'Return to Login' }).click();
});



test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
  await page.getByTitle('Notifications').click();
  await page.getByText('Notes').click();
  await page.getByText('Tasks').click();
  await page.getByText('Search').click();
  await page.getByText('Upload Download').click();
  await page.getByText('Queue').click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: ' New Quote' }).click();
  await page.locator('#dc-sect11').getByRole('button', { name: 'expand' }).click();
  await page.getByText('Restricted Medical').click();
  await page.getByRole('button', { name: 'Start Quote' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'MI991Q2025' }).click();
  await page.locator('iframe[name="classicFrame"]').contentFrame().getByRole('button', { name: 'Return to Policy' }).click();
  await page.locator('iframe[name="classicFrame"]').contentFrame().getByRole('button', { name: 'Return to Home' }).click();
  await page.getByRole('textbox', { name: 'Policy Index Type Ahead' }).click();
  await page.getByRole('textbox', { name: 'Policy Index Type Ahead' }).fill('M');
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('DR Test test2 - MI000088 (').click();
  const page1 = await page1Promise;
  await page1.goto('http://localhost/Billing/default.aspx');
  await page1.getByRole('link', { name: 'Account', exact: true }).click();
  await page1.getByRole('link', { name: 'Instalment Schedule' }).click();
  await page1.getByRole('link', { name: 'Account Settings' }).click();
  await page1.getByRole('button', { name: 'Cancel' }).click();
  await page1.locator('#productNavSelect-inputEl').click();
  await page1.getByRole('option', { name: 'Party' }).click();
  await page1.getByRole('cell', { name: 'tttttt ZZZLEGACY' }).click();
  await page1.locator('#productNavSelect-trigger-picker').click();
  await page1.getByRole('option', { name: 'Policy' }).click();
  await page1.getByRole('button', { name: '' }).click();
});


test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
  await page.getByRole('button', { name: ' Policy' }).click();
  await page.getByText('Party').click();
  await page.getByRole('link', { name: 'Tusar Sharma' }).click();
  await page.getByRole('tab', { name: 'Relationships' }).click();
  await page.getByRole('tab', { name: 'Roles' }).click();
  await page.getByRole('tab', { name: 'Group Discount' }).click();
  await page.getByRole('tab', { name: 'Refund Bank details' }).click();
  await page.getByText('Home').click();
  await page.getByRole('link', { name: 'Test' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('#tf_25').click();
  await page.locator('#tf_25').fill('Demo');
  await page.locator('#tf_25').press('Tab');
  await page.locator('#tf_26').click();
  await page.locator('#tf_26').fill('ABC ');
  await page.locator('#cb_17').click();
  await page.getByText('Partner', { exact: true }).click();
  await page.locator('dc-combobox').filter({ hasText: 'Company Type(Select)IncorporatedPartnershipSole' }).getByLabel('expand').click();
  await page.getByText('Partnership').click();
  await page.locator('#tf_27').click();
  await page.locator('#tf_27').fill('XYZ');
  await page.locator('#cb_19').click();
  await page.locator('#cb_19_options').getByText('Email').click();
  await page.locator('#tf_28').click();
  await page.locator('#tf_28').fill('4122334455');
  await page.locator('#cb_20').click();
  await page.getByText('Annulled').click();
  await page.locator('#tf_29').click();
  await page.locator('#tf_29').fill('www.exampl.com');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('#tf_25').click();
  await page.locator('#tf_25').fill('12212');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('#tf_25').click();
  await page.locator('#tf_25').fill('');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Add New Organisation').click();
  await page.getByText('Search For Person Or Place').click();
  await page.getByRole('textbox', { name: 'I\'m looking for a: ' }).click();
  await page.getByRole('textbox', { name: 'I\'m looking for a: ' }).fill('Dr');
  await page.getByRole('textbox', { name: 'I\'m looking for a: ' }).press('Enter');
});


test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
//   await page.locator('#username-inputEl').click();
//   await page.locator('#username-inputEl').fill('AioSuiteAdmin');
//   await page.locator('#password-inputEl').click();
//   await page.locator('#password-inputEl').fill('1DCTPOND$');
//   await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('http://localhost/Policy/me/express/defaultViewmodel');
  await page.locator('div').filter({ hasText: 'Loading...' }).first().click();
  await page.getByText('Choose from folder').first().click();
  await page.getByText('Queue').click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('link', { name: 'Home' }).click();
});

test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
  await page.getByTitle('Notifications').click();
  await page.locator('dc-combobox').filter({ hasText: 'StatusView AllReadUnread' }).getByLabel('expand').click();
  await page.getByText('Read', { exact: true }).click();
  await page.locator('dc-combobox').filter({ hasText: 'StatusView AllReadUnread' }).getByLabel('expand').click();
  await page.getByText('Unread').click();
  await page.getByRole('checkbox', { name: 'View Entire Database' }).check();
  await page.getByRole('textbox', { name: 'Policy Index Type Ahead' }).click();
  await page.getByRole('textbox', { name: 'Policy Index Type Ahead' }).fill('M');
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('DR tushar sharma - MI000023 (').click();
  const page1 = await page1Promise;
  await page1.goto('http://localhost/Billing/default.aspx');
  await page1.getByRole('button', { name: 'Add A Note' }).click();
  await page1.getByRole('textbox', { name: 'Title:' }).click();
  await page1.getByRole('textbox', { name: 'Title:' }).fill('Demo Note');
  await page1.getByRole('textbox', { name: 'Entry:' }).click();
  await page1.getByRole('textbox', { name: 'Entry:' }).fill('Demo Entry');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: 'Account', exact: true }).click();
  await page1.getByRole('link', { name: 'Instalment Schedule' }).click();
  await page1.getByRole('link', { name: 'Account Settings' }).click();
  await page1.getByRole('link', { name: 'Administration' }).click();
  await page1.getByRole('link', { name: 'Batch Cash Management' }).click();
  await page1.getByRole('link', { name: 'Processed Batches' }).click();
  await page1.locator('#batchNbr-inputEl').click();
  await page1.locator('#batchNbr-inputEl').fill('154');
  await page1.getByRole('button', { name: 'Display All Items' }).click();
  await page1.getByRole('link', { name: 'Tasks' }).click();
  await page1.getByRole('link', { name: 'Notifications' }).click();
  await page1.getByRole('link', { name: 'Home' }).click();
  await page1.locator('#quickSearchTextId-inputEl').click();
  await page1.locator('#quickSearchTextId-inputEl').fill('21');
  await page1.getByRole('link', { name: '' }).click();
  await page1.goto('http://localhost/Billing/default.aspx');
  await page1.locator('#productNavSelect-inputEl').click();
  await page1.getByRole('option', { name: 'Policy' }).click();
  await page1.getByTitle('Notifications').click();
  await page1.getByRole('button', { name: '' }).click();
});

test('test', async ({ page }) => {
  await page.goto('http://localhost/Policy/express.aspx');
  await page.getByRole('button', { name: ' New Quote' }).click();
  await page.getByRole('textbox', { name: 'Package Type' }).click();
  await page.getByText('Medical', { exact: true }).click();
  await page.getByRole('button', { name: 'Start Quote' }).click();
  await page.getByTitle('expand', { exact: true }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('button', { name: ' New Quote' }).click();
  await page.locator('#dc-sect3').getByRole('button', { name: 'expand' }).click();
  await page.getByText('Restricted Medical').click();
  await page.getByRole('button', { name: 'Start Quote' }).click();
  await page.getByTitle('expand', { exact: true }).click();
  await page.getByRole('button', { name: ' New Quote' }).click();
  await page.locator('#dc-sect6').getByRole('button', { name: 'expand' }).click();
  await page.getByText('Corporate Practice Cover').click();
  await page.getByRole('button', { name: 'Start Quote' }).click();
  await page.goto('http://localhost/Policy/error');
  await page.getByTitle('expand', { exact: true }).click();
  await page.getByRole('link', { name: 'Home' }).click();
});